Provision keycloak once a keycloak custom resource is created
aerogear/keycloak-operator pull request #6
Opened 2018-08-01 14:30 UTC by JameelB

## Description
Implement the provision of a Keycloak instance based on the definition of the Keycloak custom resource. A Keycloak instance and an admin user for that instance should be created. A reference to the admin credential is added to the Keycloak custom resource as well as the service instance id.

## Progress
- [x] Provision Keycloak when a Keycloak custom resource is created.
- [x] Create a secret in the same namespace for the admin credentials and add a reference of this to the Keycloak CR.
- [x] Add a reference of the Keycloak service instance to the Keycloak CR.
- [x] Set phase to `complete` and status ready to `true` once Keycloak has successfully provisioned.

## Additional Notes
Related JIRA Ticket - https://issues.jboss.org/browse/AEROGEAR-7683

**Verification Steps**
1. Create a [Keycloak custom resource](https://github.com/aerogear/keycloak-operator/blob/master/deploy/examples/keycloak_min.json) in the same namespace that the operator is deployed in.
2. Keycloak should start provisioning in that namespace.
3. A secret `keycloak-admin-cred-<hash>` should be created within the same namespace. This should have the following properties: 
```
ADMIN_USERNAME: admin
ADMIN_PASSWORD: <generated-password>
```
4. The Keycloak custom resource should have `status.phase: provisioning` and  the following properties added to its `Spec`: 
```
Spec:
   adminCredentials: <keycloak-admin-cred-ref>
   instanceID: <keycloak-service-instance-id>
   ...
```
5. Once provision is complete, the Keycloak custom resource should have `status.phase: complete`
6. Verify that you can login to the Keycloak administration console with the credentials provided in the `keycloak-admin-cred-<hash>` secret.

2018-08-01 14:30 UTC, JameelB commented
ping @dimitraz

2018-08-01 15:20 UTC, philbrookes requested changes
Looking pretty good a few small changes though.

2018-08-01 15:20 UTC, philbrookes commented on pkg/keycloak/keycloak.go
> +			return errors.New("Instance ID is not defined")
Should we set a status.Phase = failed or something here? and a status.failMessage = "instance ID not defined on keycloak object" or similar.

2018-08-01 15:20 UTC, philbrookes commented on pkg/keycloak/keycloak.go
> +				return errors.Wrap(err, "Failed to create service instance")
Should we set the phase to failed here?

2018-08-01 15:20 UTC, philbrookes commented on pkg/keycloak/keycloak.go
> +				kcCopy.Status.Phase = v1alpha1.PhaseComplete
might as well set status.ready = true here too, and remove 113 > 115

2018-08-01 15:20 UTC, philbrookes commented on pkg/keycloak/keycloak.go
> +			"ADMIN_USERNAME": "admin",
Let's pass in the username and password as arguments instead

2018-08-01 15:20 UTC, philbrookes commented on pkg/keycloak/keycloak.go
> +func (h *Handler) createAdminCredentials(namespace string) (string, error) {
Might be better to return the secret object, rather than just the name, in case we need to make further use of it in the future.

2018-08-01 15:20 UTC, philbrookes commented on pkg/keycloak/keycloak.go
> +		return "", errors.Wrap(err, "Failed to create secret for the admin credentials")
if you return the object, this should be returning nil instead of ""

2018-08-01 15:20 UTC, philbrookes commented on pkg/keycloak/keycloak.go
> +		fmt.Println("Error generating password, setting to default value", err)
I think just return the error, rather than the default password, here.

2018-08-01 15:21 UTC, philbrookes commented on pkg/keycloak/keycloak.go
> +			adminCredRef, err := h.createAdminCredentials(namespace)
Does creating this secret take a while? Would it be better to have a "creating credentials" phase, which polls for the secret to exist before moving to the provisioning phase?

2018-08-07 09:25 UTC, JameelB commented
Closing as these changes are included in https://github.com/aerogear/keycloak-operator/pull/9

2018-08-07 09:25 UTC, closed without merging