update docs for installation into cluster
aerogear/keycloak-operator pull request #7
Opened 2018-08-01 16:31 UTC by philbrookes

update docs for installing operator into a cluster rather than running it locally.

2018-08-01 19:00 UTC, JameelB requested changes
If we're using the [managed-service-broker](https://github.com/aerogear/keycloak-operator/pull/7/files#diff-b67911656ef5d18c4ae36cb6741b7965R2) namespace, shall we also change the default namespace to `managed-services-broker`?

2018-08-01 19:00 UTC, JameelB commented on README.md
> +The operator is currently deployed to a cluster manually, firstly the various CRDs need to be created in the cluster. This can be done with:
The flow of the sentence sounds a bit weird here. Wdyt about `The operator currently needs to be deployed to a cluster manually. First, the various CRDs needs to be created in the cluster. This can be done with the following command:`?

2018-08-01 19:00 UTC, JameelB commented on README.md
> +oc create -f deploy/operator.yaml -n <mananged-services-broker-namespace>
Do we also need to add `make run` here for running the operator in the targeted namespace? There's also a typo on `managed`

2018-08-01 19:00 UTC, JameelB commented on README.md
> +oc create -f deploy/rbac.yaml -n <mananged-services-broker-namespace>
typo on `managed`

2018-08-02 08:17 UTC, dimitraz commented on README.md
> +The Keycloak-Operator needs to be deployed into the same namespace as the [managed-services-broker](https://github.com/aerogear/managed-services-broker).
Maybe change Keycloak-Operator to keycloak-operator for consistency

2018-08-02 08:17 UTC, dimitraz commented on README.md
> +Now that the namespace is ready to run the keycloak-operator you can create the deployment config for it:
Should it just be deployment? (not deployment config)

2018-08-02 08:19 UTC, dimitraz commented on README.md
> +The operator is currently deployed to a cluster manually, firstly the various CRDs need to be created in the cluster. This can be done with:
What about: `The operator currently needs to be deployed manually to a running cluster. To do this, first create the necessary Custom Resource Definitions (CRDs):`

2018-08-02 10:38 UTC, dimitraz approved these changes
LGTM! :+1:

2018-08-02 10:40 UTC, merged